### ISSUE TITLE
Does vue-scrollbar work on IE9?

### ISSUE THREAD

**Issue by RyanLiu0235** [BosNaufal/vue-scrollbar#12]
Hi BosNaufal, I'm trying to use your vue-scrollbar and I am not sure if it works well on IE9. Could you please show the compatibility on README? Thank you very much.

**Comment by BosNaufal** [comment]
Hey @stop2stare, 
Thank you for giving me an issue, But I'm sorry, I have no internet explore :confused: 
So I can't check it :confused: 
Would you like to check it? or Have you check it?
