### ISSUE TITLE
Not compatible with Vue.js 2.x

### ISSUE THREAD

**Issue by anthonygore** [BosNaufal/vue-scrollbar#13]

**Comment by ruslankonev** [comment]
Inside SSR will not working - say "window" not defined inside vue-scrollbar.vue

**Comment by pwnz22** [comment]
Will it be compatible with Vue 2.x ???

**Comment by BosNaufal** [comment]
Hey Guys! @anthonygore @ruslankonev @pwnz22 
Thank you for giving me an issue~ Now You can use it with Vue2 in my [new Repo](https://github.com/BosNaufal/vue2-scrollbar)~ :grin: :+1: 
https://github.com/BosNaufal/vue-scrollbar/issues/14#issuecomment-269843230

**Comment by gholol** [comment]
@BosNaufal Works perfectly!
