### ISSUE TITLE
Module parse failed: _Scrollbar.sass You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by gholol** [BosNaufal/vue-scrollbar#14]
This is so infuriating!

>{ [Error: ./~/vue-scrollbar/src/sass/_Scrollbar.sass
>Module parse failed: D:\WTServer\WWW\node_modules\vue-scrollbar\src\sass\_Scrollbar.sass Unexpected token (3:0)
>You may need an appropriate loader to handle this file type.

There's nothing in the readme about installing any sass loaders... anyway I can compile sass just fine, so what the hell is happening? 

The loader is set, I even downloaded the sass-loader fr webpack...

      {
        test: /\.sass$/,
        loaders: ['style','css','sass']
      }

**Comment by BosNaufal** [comment]
Hey @gholol, thank you for giving me an issue.

Please check simliar issue to solve this https://github.com/BosNaufal/react-scrollbar/issues/7 :grin:

**Comment by gholol** [comment]
@BosNaufal Thanks but I moved to vue 2.1.x and this is not compatible with it

**Comment by BosNaufal** [comment]
@gholol Wait for next update then :grin: :+1:

**Comment by gholol** [comment]
@BosNaufal Will do :)

**Comment by BosNaufal** [comment]
Hey @gholol, It's your lucky day~

Would you like to review and test my new [vue2-scrollbar](https://github.com/BosNaufal/vue2-scrollbar) repo?  :grin: :+1:

**Comment by gholol** [comment]
@BosNaufal 
Oh yes, finally :dancing_men: I'll check it in few hours, when I get back from work.
