### ISSUE TITLE
Looks great but requires Jade and SASS. Why not say this? 

### ISSUE THREAD

**Issue by appodeepa** [BosNaufal/vue-scrollbar#15]
Or better yet, make it not dependent on these tools like most other Vue libraries?

**Comment by BosNaufal** [comment]
Hey @weislanes, Have you check my lastest version of vue-scrollbar? 
https://github.com/BosNaufal/vue2-scrollbar

**Comment by appodeepa** [comment]
Hi, will check it now. Thanks for making these components
