### ISSUE TITLE
"style" is a reserved attribute and cannot be used as component prop.

### ISSUE THREAD

**Issue by pavinthan** [BosNaufal/vue-scrollbar#16]
build.js:49477 [Vue warn]: "style" is a reserved attribute and cannot be used as component prop.

found in

---> <VueScrollbar>
       <Root>

**Comment by BosNaufal** [comment]
Hi @pavinthan,
Do you think is better using the Vue 2 Version instead the Vue 1? You can check my repo https://github.com/BosNaufal/vue2-scrollbar
