### ISSUE TITLE
when i use it with webpack ,it takes error

### ISSUE THREAD

**Issue by nixizhiguang** [BosNaufal/vue-scrollbar#2]
Hi, as the title says,I got an error,web pack tell me to get an loader to resolve your vue compoment.What I need to install or set ? The error seems like this:ERROR in ./~/vue-scrollbar/src/sass/_Scrollbar.sass
Module parse failed: /web/xxxx/node_modules/vue-scrollbar/src/sass/_Scrollbar.sass Unexpected token (3:0)
You may need an appropriate loader to handle this file type.

But I have set webpack with the sass loader ,like this:{
      test: /.[scss,sass]$/,
      loaders: ['style', 'css', 'sass']
    },

**Comment by BosNaufal** [comment]
Hi @nixizhiguang, Thank you for giving me an issue here~
For your problem, would you like to show me the screenshot which is showing the error? Just for full readable log :grin:

**Comment by nixizhiguang** [comment]
I got it ,my sass loader just read ".scss" file ... It resovled success,after I add ".sass" config alone. Like this: {
      test: /.sass$/,
      loaders: ['style', 'css', 'sass']
    },
Thanks for your reply!
