### ISSUE TITLE
It seems before destory method has something wrong

### ISSUE THREAD

**Issue by nixizhiguang** [BosNaufal/vue-scrollbar#3]
Hi，I am back again. In the file named 'horizontal-scrollbar.vue',u write a method beforeDestroy(),u may be want to remove all the event listener before the compoment destory.But u used addEventListener....should it be removeEventListener? Because in another file ,u write removeEventListener...And, my designer said ,I should add two arrow used to adjust the scrollbar,I do not know how to modify the code,because I do not know how to use jade ...If you are willing to...Can u give me an normal version without jade ?
Thanks for your help!

**Comment by nixizhiguang** [comment]
My English is not very good, I hope you can understand...

**Comment by BosNaufal** [comment]
Hi @nixizhiguang, Sorry for the slow response~
It seems I got little typo there :grin: You can give me a pull request about that.

Do you want the HTML template version? Hmmm... I can't promise to you. But I think It wortIh to work on.

**Comment by nixizhiguang** [comment]
I have used the online transform to get html version,and it works well.Thank you for your help!

**Comment by BosNaufal** [comment]
Whoooa! you're so creative person~ :smile: 
Glad to hear it :grin:
