### ISSUE TITLE
Not compatible with sidescrolling mouse

### ISSUE THREAD

**Issue by svenluijten** [BosNaufal/vue-scrollbar#6]
Hi, trying out [the live demo](https://bosnaufal.github.io/vue-scrollbar/) I noticed scrolling sideways (with the Logitech MX Master) didn't actually scroll to the side. Instead, it just scrolls me up if it's not at the top already. 

Quick demo where I scroll down and then try scrolling sideways. I never (intentionally) scroll upwards in this gif: 

![vue-scrollbar](https://cloud.githubusercontent.com/assets/11269635/16356583/d508e87a-3add-11e6-8d6c-c20d48c70bf1.gif)

**Comment by BosNaufal** [comment]
Hi @svenluijten, Sorry for slow response here and Thank you for trying vue-scrollbar :grin: 
To scroll sideways You should hold the shift key while scrolling. Have you? Let me know it soon. :grin:
