### ISSUE TITLE
Issue with long horizontal scroll

### ISSUE THREAD

**Issue by pbelyaev** [BosNaufal/vue-scrollbar#7]
Hello! 
When I was trying to use this component for a long horizontal scroll it didn't work. 
I realized what's wrong with that. Look at this method:

``` javascript
handleChangePosition(vScrollbar, orientation){
        // Convert Percentage to Pixel
        let next = vScrollbar / 100 * this.scrollAreaHeight
        if( orientation == 'vertical' ) this.normalizeVertical(next)
        if( orientation == 'horizontal' ) this.normalizeHorizontal(next)
}
```

I think `next` variable should have condition either and also using different scrollArea values. At least it works for me.

``` javascript
handleChangePosition(vScrollbar, orientation){
        // Convert Percentage to Pixel
        let next = vScrollbar / 100 * (orientation == 'vertical' ? this.scrollAreaHeight : this.scrollAreaWidth)
        if( orientation == 'vertical' ) this.normalizeVertical(next)
        if( orientation == 'horizontal' ) this.normalizeHorizontal(next)
}
```

**Comment by pbelyaev** [comment]
**How to check the issue?**
Just try to create a wrapper div with any width but without any height limits so vertical scroll won't be showed. Then create a content div with 9000+ px width and try to render that.

**Comment by BosNaufal** [comment]
Hey @pbelyaev, Thank you so much for giving me an issue and giving me its solution at the same time! thanks! :grin: :+1:
